name: CI

on:
  push:
    branches:
      - master

jobs:
    FrontDeploy:
        name: FrontDeploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.11.x
                  registry-url: "https://registry.npmjs.org"
            - name: Install Dependencies
              run: yarn
            - name: Build
              run: |
                  npm install
                  npm install -g firebase-tools
                  npm run build
            - name: deploy to Firebase Hosting
              run: |
                  firebase deploy --token $FIREBASE_TOKEN
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}